# Generated by Django 4.2.6 on 2023-10-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_company',
        ),
    ]
